/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import model.MySQL;

/**
 *
 * @author User
 */
public class Add_Appointment extends javax.swing.JFrame {
    private static final HashMap<String, String> docMap = new HashMap<>();
    /**
     * Creates new form Add_Appointment
     */
    public Add_Appointment() {
        initComponents();
        DoctorsList();
    }
private void DoctorsList() {
    try {
        ResultSet resultset = MySQL.execute("SELECT * FROM `user` WHERE `user_role_id` = '2'");
        Vector<String> vector = new Vector<>();
        vector.add("SELECT");

        while (resultset.next()) {
            String fname = resultset.getString("fname");
            String lname = resultset.getString("lname");
            String fullName = "Dr "+fname + " " + lname;

            vector.add(fullName);
            
            // Store user_id or fullName as key, role_id as value
            docMap.put(resultset.getString("user_id"), fullName);
        }

        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>(vector);
        doc_ComboBox1.setModel(model1);

    } catch (Exception e) {
        e.printStackTrace(); // Show error for debugging
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        age_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        title_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        l_name_tx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mobile_tx = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        details_txt = new javax.swing.JTextField();
        f_name_tx1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        doc_ComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        age_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txtActionPerformed(evt);
            }
        });
        getContentPane().add(age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ADD APPOINTMENT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel6.setText("First Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        getContentPane().add(title_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 270, 30));

        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        l_name_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_name_txActionPerformed(evt);
            }
        });
        getContentPane().add(l_name_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 130, 30));

        jLabel8.setText("Mobile");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        mobile_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_txActionPerformed(evt);
            }
        });
        getContentPane().add(mobile_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        jLabel10.setText("Title");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 10));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 130, 30));

        jLabel12.setText("Age");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 20));
        getContentPane().add(details_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 270, 30));
        getContentPane().add(f_name_tx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, 30));

        jLabel13.setText("Details");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        getContentPane().add(address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, 30));

        jLabel14.setText("Doctor");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        doc_ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_ComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(doc_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 130, 30));

        jLabel15.setText("Chanel Date");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/back_btn.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(211, 227, 217));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ADD");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/Add_Green_btn.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/bg3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void l_name_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_name_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_name_txActionPerformed

    private void mobile_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_txActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
      String fname = f_name_tx1.getText();
        String lname = l_name_tx.getText();
         String username = address_txt.getText();
        String mobile = mobile_tx.getText();
         String age = age_txt.getText();
        String title = title_txt.getText();
         String details= details_txt.getText();
        String doctor = String.valueOf(doc_ComboBox1.getSelectedItem()); 
        String sheduleddate = jDateChooser1.getDateFormatString();

       

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void doc_ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_ComboBox1ActionPerformed

    private void age_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField age_txt;
    private javax.swing.JTextField details_txt;
    private javax.swing.JComboBox<String> doc_ComboBox1;
    private javax.swing.JTextField f_name_tx1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField l_name_tx;
    private javax.swing.JTextField mobile_tx;
    private javax.swing.JTextField title_txt;
    // End of variables declaration//GEN-END:variables
}
