package view;


import auth.SessionManager;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import model.MySQL;
import java.sql.ResultSet;
import model.User_Bean;
import model.User;
import model.UserFactory;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_lable = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        logo_sm = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_lable.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Login_lable.setForeground(new java.awt.Color(51, 51, 51));
        Login_lable.setText("LOGIN");
        getContentPane().add(Login_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jTextField1.setBackground(new java.awt.Color(249, 255, 250));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 260, 40));

        jPasswordField1.setBackground(new java.awt.Color(249, 255, 250));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginUIComponents/Login_btn.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        logo_sm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginUIComponents/Logo_sm.png"))); // NOI18N
        getContentPane().add(logo_sm, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        bg1.setBackground(new java.awt.Color(249, 255, 250));
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginUIComponents/Bg1-light-green.png"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String username = jTextField1.getText();
        String password = String.valueOf(jPasswordField1.getPassword());

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter your username", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter your password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {

                ResultSet resultSet = MySQL.execute(
                        "SELECT * FROM user WHERE username='" + username + "' AND password='" + password + "'"
                );

                if (resultSet.next()) {
                    String userName = resultSet.getString("username");
                    String fname = resultSet.getString("fname");
                    String lname = resultSet.getString("lname");
                    int roleId = resultSet.getInt("user_role_id");  // ✅ Get role id from DB

                    // Create user bean
                    User_Bean user_Bean = new User_Bean();
                    user_Bean.setUsername(userName);
                    user_Bean.setFname(fname);
                    user_Bean.setLname(lname);
                    user_Bean.setRoleId(roleId);

                    User currentUser = UserFactory.createDecoratedUser(user_Bean);

                    SessionManager.setCurrentUser(currentUser);

                    switch (roleId) {
                        case 1:
                            DashboardAdmin adminDashboard = new DashboardAdmin();
                             adminDashboard.setUserBean(user_Bean);
                            adminDashboard.setVisible(true);
                            break;
                        case 2:
                            DashboardDoctor doctorDashboard = new DashboardDoctor();
                            doctorDashboard.setUserBean(user_Bean);
                            doctorDashboard.setVisible(true);
                            break;
                       case 3:
                            DashboardPharmacy pharmacyDashboard = new DashboardPharmacy();
                            pharmacyDashboard.setUserBean(user_Bean);
                            pharmacyDashboard.setVisible(true);
                            break;
                              case 4:
                            DashboardDoctor nurseDashboard = new DashboardDoctor();
                            nurseDashboard.setUserBean(user_Bean);
                            nurseDashboard.setVisible(true);
                            break;
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_lable;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo_sm;
    // End of variables declaration//GEN-END:variables
}
