package view;

import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import model.MySQL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author User
 */
public class MedicineForm extends javax.swing.JPanel {

    

    private DashboardAdmin dashboardAdmin;

    /**
     * Creates new form Doctor_Regi
     */
    public MedicineForm(DashboardAdmin dashboardAdmin) {
        this.dashboardAdmin = dashboardAdmin;
        initComponents();

    }

    private void reset() {
        name_tx.setText("");
        qantity_ftx.setText("");
        unitPrice_ftx.setText("");
        jTextPane1.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        qantity_ftx = new javax.swing.JFormattedTextField();
        name_tx = new javax.swing.JTextField();
        unitPrice_ftx = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(780, 420));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("MEDICINE FORM");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel7.setText("Quantity");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel8.setText("Unit Price");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 70, -1));

        jLabel9.setText("Description");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setText(" Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        qantity_ftx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        add(qantity_ftx, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 210, 40));
        add(name_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 210, 40));

        unitPrice_ftx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        add(unitPrice_ftx, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 210, 40));

        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 460, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(211, 227, 217));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADD");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 333, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/Add_Green_btn.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/bg3.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        String name = name_tx.getText();
        String qty = qantity_ftx.getText();
        String up = unitPrice_ftx.getText();
        String description = jTextPane1.getText();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Medicine Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Quantity", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!qty.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Quantity must be a number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (up.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Unit Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!up.matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "Invalid Unit Price (e.g., 150 or 150.50)", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                MySQL.execute(
                        "INSERT INTO `medicine` (`name`, `qty`, `unit_price`, `description`) "
                        + "VALUES ('" + name + "', '" + qty + "', '" + up + "', '" + description + "');"
                );

                reset();

                Successfull_Alert successfull_Alert = new Successfull_Alert();
                successfull_Alert.Alert_success_txt.setText("Medicine Registered Successfully..!");
                successfull_Alert.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
     
    }//GEN-LAST:event_jLabel15MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField name_tx;
    private javax.swing.JFormattedTextField qantity_ftx;
    private javax.swing.JFormattedTextField unitPrice_ftx;
    // End of variables declaration//GEN-END:variables
}
