
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import model.MySQL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author User
 */
public class Doct_Table extends javax.swing.JPanel {
     private static final HashMap<String, String> specialistatMap = new HashMap<>();
    private  DashboardAdmin dashboardAdmin;

    /**
     * Creates new form Doctor_Regi
     */
    public Doct_Table(DashboardAdmin dashboardAdmin) {
        this.dashboardAdmin=dashboardAdmin;
        initComponents();
        RollList();
    }
private void RollList() {
        try {
            ResultSet resultset = MySQL.execute("SELECT * FROM `user_role`");
            Vector<String> vector = new Vector<>();
            vector.add("SELECT");
            while (resultset.next()) {
                vector.add(resultset.getString("role"));
                specialistatMap.put(resultset.getString("role"), resultset.getString("role_id"));
            }
            DefaultComboBoxModel model1 = new DefaultComboBoxModel(vector);
            spe_ComboBox1_tx.setModel(model1);
            
        } catch (Exception e) {
        }
   
        f_name_tx.setBackground(new java.awt.Color(0, 0, 0, 1));
        l_name_tx.setBackground(new java.awt.Color(0, 0, 0, 1));
       
        mobile_tx.setBackground(new java.awt.Color(0, 0, 0, 1));
       
        username_tx.setBackground(new java.awt.Color(0, 0, 0, 1));
        PasswordField_tx.setBackground(new java.awt.Color(0, 0, 0, 1));
        spe_ComboBox1_tx.setBackground(new java.awt.Color(0, 0, 0, 1));
    }
private void reset() {
        f_name_tx.setText("");
        l_name_tx.setText("");
        mobile_tx.setText("");
        PasswordField_tx.setText("");
    
        username_tx.setText("");
       
     
        spe_ComboBox1_tx.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mobile_tx = new javax.swing.JTextField();
        username_tx = new javax.swing.JTextField();
        l_name_tx = new javax.swing.JTextField();
        f_name_tx = new javax.swing.JTextField();
        PasswordField_tx = new javax.swing.JPasswordField();
        spe_ComboBox1_tx = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(780, 420));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("SIGN UP");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel7.setText("Last Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel8.setText("Mobile");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel9.setText("Username");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel11.setText("Role");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jLabel6.setText("First Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        add(mobile_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 210, 40));

        username_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txActionPerformed(evt);
            }
        });
        add(username_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, 40));

        l_name_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_name_txActionPerformed(evt);
            }
        });
        add(l_name_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 210, 40));
        add(f_name_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 210, 40));
        add(PasswordField_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 210, 40));

        add(spe_ComboBox1_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/Signup_btn.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/back_btn.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUiComponents/bg3.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(780, 420));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void l_name_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_name_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_name_txActionPerformed

    private void username_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        String fname = f_name_tx.getText();
        String lname = l_name_tx.getText();
        String mobile = mobile_tx.getText();
        String password = String.valueOf(PasswordField_tx.getPassword());
   
        String username = username_tx.getText();
        String specialist = String.valueOf(spe_ComboBox1_tx.getSelectedItem());
        
        if (fname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter  First Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (lname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter  Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter  Mobile", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!mobile.matches("^07[012345678]{1}[0-9]{7}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter  username", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter  Password", "Warning", JOptionPane.WARNING_MESSAGE);
        }   else if (specialist.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select Specialist At", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                MySQL.execute("INSERT INTO `user` (`fname`, `lname`, `mobile`, `username`, `password`, `user_role_id`)\n"
                        + "VALUES ('" + fname + "', '" + lname + "', '" + mobile + "', '" + username + "', '" + password + "', '" + specialistatMap.get(specialist) + "');");
                reset();
//              Register_Successfully_info Rsi =new Register_Successfully_info();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField_tx;
    private javax.swing.JTextField f_name_tx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField l_name_tx;
    private javax.swing.JTextField mobile_tx;
    private javax.swing.JComboBox<String> spe_ComboBox1_tx;
    private javax.swing.JTextField username_tx;
    // End of variables declaration//GEN-END:variables
}
